" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set background=dark "light is also available
colorscheme solarized
set guifont=Inconsolata:h18
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set lines=30 columns=150          " Window dimensions.
set guioptions-=r                 " Don't show right scrollbar



