" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

"if has("gui_mac") || has("gui_macvim")
"  macmenu &File.New\ Tab     key=<Nop>
"  map <silent><D-t> :FufFile **/<CR>
"endif

set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar



