" Example Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()


syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set history=100
set undolevels=1000               "use muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class


""""""""""""""""""
" FORMATING
""""""""""""""""""
set pastetoggle=<F2>             " Press F2 before paste from clipboard
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs
set showmatch  					 " Show matching brackets.
set mat=5  						 " Bracket blinking.
set laststatus=2                 " Show the status line all the time
set autoindent
imap <Tab> <C-N>                 " Autocompletion triggered by Ctrl+N
imap <S-Tab> <C-P>

" Indentention
vmap <Tab> >gv
vmap <S-Tab> <gv

" Quickly edit/reload th vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>rv :so $MYVIMRC<CR> <bar> :echo ".vimrc reloaded"<CR>


" Cmd+Enter like in textmate"
imap <D-Enter> <Esc>A<CR> 


" Remove a line like in Emacs
imap <D-d> <Esc>ddi

" gvim specific
set mousehide  " Hide mouse after chars typed
set mouse=a  " Mouse in all modes


" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P


set background=dark "light is also available
colorscheme solarized


set guifont=Inconsolata:h18

" Tab mappings 
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" Tab-complete file names
set wildmode=list:longest


" FuzzyFinder plugin (D-T) has been mapped in gvimrc as well
map <Leader>f :FufFile<Enter>

" See the CTags (class and methods) belonging to the current buffer
map <Leader>t :TlistToggle<Enter>

"""""""""""""""""""""""""""""""""""""""""""""      
" => MRU Plugin (Most Recent Used Documents)
"""""""""""""""""""""""""""""""""""""""""""""      
let MRU_Max_Entries = 20 
map <leader>r <Esc>:MRU<CR> "q(uit)

"""""""""""""""""""""""""""""""""""""""""""""      
" => See all open buffers
"""""""""""""""""""""""""""""""""""""""""""""  
"nnoremap <leader>b :ls<CR>:buffer<Space>
map <leader>b <ESC><leader>be<CR>

" Useful for those times where you forgot to sudo before editing a file
cmap w!! w !sudo tee % > /dev/null


" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

"Swith between windows
" TODO

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
autocmd BufNewFile,BufRead *_spec.rb compiler rspec




